### ISSUE TITLE
BrightSun2020CSDs and BrightSun2020CSDc declare the same function

### ISSUE THREAD

**Issue by cwhanse** [JamieMBright/csd-library#2]
Both declare  `BrightSun2020CSDc`

**Comment by JamieMBright** [comment]
Thank's @cwhanse 
I have fixed this issue.

**Comment by cwhanse** [comment]
@JamieMBright  the two files BrightSun2020CSDc.m and BrightSun2020CSDs.m appear identical except for the function name. Which one implements the clear-sky equivalent detection, and which implements the cloudless sky detection?

**Comment by JamieMBright** [comment]
Hi Cliff,
Yeah they are basically the same. It was a distinction Chris G wanted to have line of sight CSD models and cloudless sky models (as declared by our paper together https://doi.org/10.1016/j.rser.2019.04.027)

The reality is the same process happens with just different criteria on the "close to cloud" durational filters. which are:

```% Duration filter strictness
% First durational window. Higher time but lower strictness.
% The window is the duration size of the window in mins. 
window_1st_filter = 90;
% Tolerance is the permissible number of CSD periods within the window. 
tolerance_1st_filter = 10;

% Second durational window. Lower time but higher strictness.
window_2nd_filter = 30;
tolerance_2nd_filter = 0;
```
for CSDc and :

```% Duration filter strictness
% First durational window. Higher time but lower strictness.
% The window is the duration size of the window in mins. 
window_1st_filter = 1;
% Tolerance is the permissible number of CSD periods within the window. 
tolerance_1st_filter = 1;

% Second durational window. Lower time but higher strictness.
window_2nd_filter = 1;
tolerance_2nd_filter = 1;
```

for CSDs, note that 1 is the same as the filter not being applied, wheras 0 breaks it in matlab. There is probably a nuance to the indexing with python vs matlab that change this.

Essentially durational filters off = line-of-sight CSDs method, filters on = cloudless CSDc method.

Hope that helps?
